version: '3.8'

services:
  web:
    build: .  # Indica que a imagem deve ser construída a partir do Dockerfile no diretório atual
    ports:
      - "80:80"  # Mapeia a porta 80 do contêiner para a porta 80 do host
    volumes:
      - ./html:/usr/share/nginx/html  # Refletir alterações em arquivos HTML
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Refletir alterações na configuração do Nginx
    networks:
      - webnet

networks:
  webnet:


